CREATE SCHEMA IF NOT EXISTS `inova_bank`;

CREATE TABLE IF NOT EXISTS `inova_bank`.`user` (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `cpf` VARCHAR(14) NOT NULL UNIQUE,
  `password` VARCHAR(32),
  `age` INT NOT NULL,
  `active` TINYINT NOT NULL
);